export const cardsDatabase = [
  { cardId: '1', name: 'Adorned Pouncer', power: '1', toughness: '1', oracleText: 'Double strike Eternalize 3WhiteWhite (3WhiteWhite, Exile this card from your graveyard: Create a token thats a copy of it, except its a 4/4 black Zombie Cat with no mana cost. Eternalize only as a sorcery.)', cost: '1W', imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=430691&type=card' },
  { cardId: '2', name: 'Aerial Responder', power: '2', toughness: '3', oracleText: 'Flying, vigilance, lifelink', cost: '1WW', imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417575&type=card' },
  { cardId: '3', name: 'Aethersphere Harvester', power: '3', toughness: '5', oracleText: 'When Aethersphere Harvester enters the battlefield, you get', cost: '3', imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423809&type=card' },
  { cardId: '4', name: 'Barals Expertise', power: '', toughness: '', oracleText: '', cost: '3BB', imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423696&type=card' },
  { cardId: '5', name: 'Dovin Baan', power: '', toughness: '', oracleText: '+1: Until your next turn, up to one target creature gets -3/-0 and its activated abilities cant be activated. −1: You gain 2 life and draw a card. −7: You get an emblem with "Your opponents cant untap more than two permanents during their untap steps', cost: '2WB', imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417752&type=card' },
  { cardId: '6', name: 'Dread Wanderer', power: '2', toughness: '1', oracleText: 'Dread Wanderer enters the battlefield tapped.', cost: 'B', imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=426790&type=card' },
  { cardId: '7', name: 'Saheeli Rai', power: '', toughness: '', oracleText: '', cost: '1BR', imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417759&type=card' },
];
