version: '3.7'
services:
  web:
    container_name: 'mtg-card-organizer-web'
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    networks:
      - proxy
    restart: always

  api:
    container_name: 'mtg-card-organizer-api'
    build:
      context: ./backend/
      dockerfile: Dockerfile
    networks:
      - proxy
    volumes:
      - "db:/var/mtgdb"
    restart: always

volumes:
  db:

networks:
  proxy:
    name: proxy