version: '3'
services:
  mtg-card-organizer-db:
    build:
      context: ./
      dockerfile: ./mtg-card-organizer-db/dockerfile
    ports:
      - "3001:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - /opt/dockershare/mtg-card-organizer-db:/var/opt/mssql/data

  mtg-card-organizer-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: ../../
      dockerfile: ./docker/production/mtg-card-organizer-api/dockerfile
    ports:
      - "3002:80"
      
  mtg-card-organizer-web:
    build:
      context: ../../mtg-card-organizer
      dockerfile: ../docker/production/mtg-card-organizer-web/dockerfile
    ports:
      - "80:80"