# Container 1: Build
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app
COPY ./MtgCardOrganizer.Api/MtgCardOrganizer.Api.csproj ./MtgCardOrganizer.Api/
COPY ./MtgCoreLib/MtgCoreLib.csproj ./MtgCoreLib/
WORKDIR /app/MtgCardOrganizer.Api/
RUN dotnet restore

WORKDIR /app
COPY ./MtgCardOrganizer.Api/ ./MtgCardOrganizer.Api/
COPY ./MtgCoreLib/ ./MtgCoreLib/
WORKDIR /app/MtgCardOrganizer.Api/
RUN dotnet publish -c Local -o out

# Container 2: Deployment
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/MtgCardOrganizer.Api/out .
ENTRYPOINT ["dotnet", "MtgCardOrganizer.Api.dll"]
