// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgCardOrganizer.Core.Initialization;

namespace MtgCardOrganizer.Core.Migrations
{
    [DbContext(typeof(MtgCardOrganizerContext))]
    [Migration("20180811223542_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Cards.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConvertedManaCost");

                    b.Property<string>("ManaCost");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OracleText");

                    b.Property<string>("Power");

                    b.Property<string>("Toughness");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Cards.CardInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CardSetId");

                    b.Property<bool>("Foil");

                    b.Property<bool>("Promo");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.ToTable("CardInstances");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Cards.CardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Artist")
                        .IsRequired();

                    b.Property<int?>("CardId");

                    b.Property<string>("MultiverseId");

                    b.Property<string>("Num");

                    b.Property<int>("Rarity");

                    b.Property<int?>("SetId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Cards.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Collections.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OwnerUserId");

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Collections.CollectionCardLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardInstanceId");

                    b.Property<int>("CollectionId");

                    b.HasKey("Id");

                    b.HasIndex("CardInstanceId")
                        .IsUnique();

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionCardLinks");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Collections.CollectionUserLink", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("CollectionId");

                    b.Property<int>("Permission");

                    b.HasKey("UserId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionUserLinks");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Other.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Cards.CardInstance", b =>
                {
                    b.HasOne("MtgCardOrganizer.Core.Entities.Cards.CardSet", "CardSet")
                        .WithMany("CardInstances")
                        .HasForeignKey("CardSetId");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Cards.CardSet", b =>
                {
                    b.HasOne("MtgCardOrganizer.Core.Entities.Cards.Card", "Card")
                        .WithMany("CardSets")
                        .HasForeignKey("CardId");

                    b.HasOne("MtgCardOrganizer.Core.Entities.Cards.Set", "Set")
                        .WithMany("CardSetInfos")
                        .HasForeignKey("SetId");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Collections.Collection", b =>
                {
                    b.HasOne("MtgCardOrganizer.Core.Entities.Collections.Collection", "Parent")
                        .WithMany("SubCollections")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Collections.CollectionCardLink", b =>
                {
                    b.HasOne("MtgCardOrganizer.Core.Entities.Cards.CardInstance", "CardInstance")
                        .WithOne("CollectionCardLink")
                        .HasForeignKey("MtgCardOrganizer.Core.Entities.Collections.CollectionCardLink", "CardInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MtgCardOrganizer.Core.Entities.Collections.Collection", "Collection")
                        .WithMany("CollectionCardLinks")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MtgCardOrganizer.Core.Entities.Collections.CollectionUserLink", b =>
                {
                    b.HasOne("MtgCardOrganizer.Core.Entities.Collections.Collection", "Collection")
                        .WithMany("CollectionUserLinks")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
